<a href="https://colab.research.google.com/github/MaheswaraPradeep/python-new/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Advantages of numpy
1. Allows several math ops
2. faster operations

In [ ]:
import numpy as np

List vs numpy time taken

In [ ]:
from time import process_time

Time taken by list

In [ ]:
list1=[i for i in range(1000000)]
start_time=process_time()
list1=[i+5 for i in list1]
end_time=process_time()
print(end_time-start_time)

0.0722972460000002


In [ ]:
np_array=np.array([i for i in range(1000000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.001354073999999983


Numpy arrays

In [ ]:
list2=[1,2,3,4,5]
print(list2)
type(list2)

[1, 2, 3, 4, 5]


list

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating 1d array
a=np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [ ]:
a.shape # shape is a fun used to print colums and rows in a array

(4,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b.ndim)

2


In [ ]:
b.shape

(2, 4)

In [ ]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float) # dtype is used to mention other data types than int. by default it is int
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial place holders in numpy array

In [ ]:
# create numpy array of zeroes
x=np.zeros((4,5)) # zeros is a function for all values zeros and 4,5 is 4 rows and 5 cols
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create numpy array of 1s
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# create array of a particular value
z=np.full((5,5),5) # full is a func used to get all values of a specified value other than 0 or 1
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
# create identity matrix
a=np.eye(4) # eye is func used to print identity matrix. only one arg is given since identity matrix is a square matrix
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create numpy array with random values
b=np.random.random((3,4)) # all random vals will be btw 0 to 1
print(b)

[[0.35956782 0.90925676 0.7091323  0.92225106]
 [0.56654121 0.26280467 0.04591846 0.31499362]
 [0.12390046 0.46585445 0.10019096 0.80423548]]


In [ ]:
# random values array with integers within a range
c=np.random.randint(1,100,(3,3))
print(c)

[[61 64 20]
 [90  5 81]
 [33 39 81]]


In [ ]:
# arry of evenly spaced values --- specify no of values wanted
d=np.linspace(1,100,6) # values btw 1 to 100, 6 values needed
print(d)

[  1.   20.8  40.6  60.4  80.2 100. ]


In [ ]:
# arry of evenly spaced values --- specify step value
e=np.arange(10,100,5) # evenly spaced btw 1 to 100 of difference of 5
print(e)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
# convert list to a numpy array
list2=[10,23,45,67,89]
arr=np.asarray(list2)
print(arr)
type(arr)

[10 23 45 67 89]


numpy.ndarray

Analysing numpy array

In [ ]:
c=np.random.randint(10,20,(5,5))
print(c)

[[16 17 14 10 19]
 [12 16 15 12 14]
 [12 14 17 12 13]
 [17 13 10 14 17]
 [18 12 10 15 16]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# no of dimensions
print(c.ndim) # says whether it is 2d or 3d array etc

2


In [ ]:
# check no of elements in an array
print(c.size)

25


In [ ]:
# checking data type of values in array
print(c.dtype) # 64 bit integer data type

int64


Math operation on np array

In [ ]:
list1=[1,2,3,4,5]
list2=[45,34,12,11]
print(list1+list2) # element wise addition not happening. only concatenation happens in list

[1, 2, 3, 4, 5, 45, 34, 12, 11]


In [ ]:
a=np.random.randint(1,20,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b) # element wise addition happens
print(a-b)
print(a*b)
print(a//b)

[[12 18  4]
 [14  9  6]
 [ 5  9 16]]
[[16 17 19]
 [10 14 15]
 [11 14 11]]
[[28 35 23]
 [24 23 21]
 [16 23 27]]
[[ -4   1 -15]
 [  4  -5  -9]
 [ -6  -5   5]]
[[192 306  76]
 [140 126  90]
 [ 55 126 176]]
[[0 1 0]
 [1 0 0]
 [0 0 1]]


In [ ]:
# another way to do basic math ops
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[28 35 23]
 [24 23 21]
 [16 23 27]]
[[ -4   1 -15]
 [  4  -5  -9]
 [ -6  -5   5]]
[[192 306  76]
 [140 126  90]
 [ 55 126 176]]
[[0.75       1.05882353 0.21052632]
 [1.4        0.64285714 0.4       ]
 [0.45454545 0.64285714 1.45454545]]


Array manipulations

In [ ]:
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 2 6]
 [7 7 4]]
(2, 3)


In [ ]:
# transpose
b=np.transpose(a)
print(b)

[[6 7]
 [2 7]
 [6 4]]


In [ ]:
arr=np.array((1,2,3,45))
print(arr)

[ 1  2  3 45]


In [ ]:
arr=np.array([[[1,2,3,4],[6,7,89,99]],[[1,2,3,4],[5,56,7,8]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3  4]
  [ 6  7 89 99]]

 [[ 1  2  3  4]
  [ 5 56  7  8]]]
3


In [ ]:
arr=np.array([(1,2,3,4),(2,3,4,5),(1,2,3,4)])
print(arr.ndim)

2


In [ ]:
arr=np.array([[1,2,3,4],[2,3,4,5]])
print(arr[0,-1])

4


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[1:])